using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Farm_Tracker
{
    class Variables
    {
        public static string CONNECTIONSTRING = "Data Source=ZAKS-XPS15/FARMTRACKER;Initial Catalog=Farm_Tracker;Integrated Security=True";
    }

    
//#####  Color Palette by Paletton.com
//#####  Palette URL: http://paletton.com/#uid=12j0u0knhobdyyjiSrOqSjEvReh


//*** Primary color:

//   shade 0 = #8EB531 = rgb(142,181, 49) = rgba(142,181, 49,1) = rgb0(0.557,0.71,0.192)
//   shade 1 = #D2F18B = rgb(210,241,139) = rgba(210,241,139,1) = rgb0(0.824,0.945,0.545)
//   shade 2 = #ACD056 = rgb(172,208, 86) = rgba(172,208, 86,1) = rgb0(0.675,0.816,0.337)
//   shade 3 = #6E9318 = rgb(110,147, 24) = rgba(110,147, 24,1) = rgb0(0.431,0.576,0.094)
//   shade 4 = #4B6B00 = rgb( 75,107,  0) = rgba( 75,107,  0,1) = rgb0(0.294,0.42,0)


//#####  Generated by Paletton.com (c) 2002-2014


}
